= Grotag 

Grotag views Amigaguide documents or converts them to HTML and DocBook XML. Additionally it can validate and pretty print such documents.

This is a fork of the original Grotag which intends to modernize the code a bit, fix some bugs, a v40 support and AsciiDoc saveas.

== Getting Started

=== Prerequisites

What things you need to install the software and how to install them

....
 Java 8
....

=== Installing

First build the project.
....
./gradlew clean build
....

Now, under build/libs you will find a fat grotag.jar.
Run it with

....
java -jar -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true NAMEOFTHEFGROTAG.JAR
....

== Running the tests

....
./gradlew clean check
....


== Built With

TODO

== Contributing

TODO

== Versioning

We use http://semver.org/[SemVer] for versioning. For the versions
available, see the https://github.com/your/project/tags[tags on this
repository].

== Authors

* *Thomas Aglassinger* - _Initial work, creator_ 
https://github.com/roskakori[roskakori]

TODO

== License

This project is licensed under the GPLv3 License - see the link:LICENSE[LiCENSE] file
for details

== Acknowledgments

* Thomas for the original project
* Amiga OS and the Amiga comuunity for still being fascinating after all these years.
